//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship4", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.patient), "analis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.analis), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship1", "doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.doctor), "healing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.healing), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship3", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.patient), "healing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.healing), true)]

#endregion

namespace hospital
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hc_dbConect : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hc_dbConect object using the connection string found in the 'hc_dbConect' section of the application configuration file.
        /// </summary>
        public hc_dbConect() : base("name=hc_dbConect", "hc_dbConect")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hc_dbConect object.
        /// </summary>
        public hc_dbConect(string connectionString) : base(connectionString, "hc_dbConect")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hc_dbConect object.
        /// </summary>
        public hc_dbConect(EntityConnection connection) : base(connection, "hc_dbConect")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<analis> analis
        {
            get
            {
                if ((_analis == null))
                {
                    _analis = base.CreateObjectSet<analis>("analis");
                }
                return _analis;
            }
        }
        private ObjectSet<analis> _analis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<doctor> doctor
        {
            get
            {
                if ((_doctor == null))
                {
                    _doctor = base.CreateObjectSet<doctor>("doctor");
                }
                return _doctor;
            }
        }
        private ObjectSet<doctor> _doctor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<healing> healing
        {
            get
            {
                if ((_healing == null))
                {
                    _healing = base.CreateObjectSet<healing>("healing");
                }
                return _healing;
            }
        }
        private ObjectSet<healing> _healing;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<patient> patient
        {
            get
            {
                if ((_patient == null))
                {
                    _patient = base.CreateObjectSet<patient>("patient");
                }
                return _patient;
            }
        }
        private ObjectSet<patient> _patient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<spec> spec
        {
            get
            {
                if ((_spec == null))
                {
                    _spec = base.CreateObjectSet<spec>("spec");
                }
                return _spec;
            }
        }
        private ObjectSet<spec> _spec;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the analis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToanalis(analis analis)
        {
            base.AddObject("analis", analis);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the doctor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodoctor(doctor doctor)
        {
            base.AddObject("doctor", doctor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the healing EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohealing(healing healing)
        {
            base.AddObject("healing", healing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the patient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopatient(patient patient)
        {
            base.AddObject("patient", patient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the spec EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTospec(spec spec)
        {
            base.AddObject("spec", spec);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="analis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class analis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new analis object.
        /// </summary>
        /// <param name="id_analis">Initial value of the id_analis property.</param>
        /// <param name="id_patient">Initial value of the id_patient property.</param>
        public static analis Createanalis(global::System.Int32 id_analis, global::System.Int32 id_patient)
        {
            analis analis = new analis();
            analis.id_analis = id_analis;
            analis.id_patient = id_patient;
            return analis;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_analis
        {
            get
            {
                return _id_analis;
            }
            set
            {
                if (_id_analis != value)
                {
                    Onid_analisChanging(value);
                    ReportPropertyChanging("id_analis");
                    _id_analis = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_analis");
                    Onid_analisChanged();
                }
            }
        }
        private global::System.Int32 _id_analis;
        partial void Onid_analisChanging(global::System.Int32 value);
        partial void Onid_analisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                Onid_patientChanging(value);
                ReportPropertyChanging("id_patient");
                _id_patient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_patient");
                Onid_patientChanged();
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String conclusion
        {
            get
            {
                return _conclusion;
            }
            set
            {
                OnconclusionChanging(value);
                ReportPropertyChanging("conclusion");
                _conclusion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("conclusion");
                OnconclusionChanged();
            }
        }
        private global::System.String _conclusion;
        partial void OnconclusionChanging(global::System.String value);
        partial void OnconclusionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship4", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("hc_dbModel.Relationship4", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="doctor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class doctor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new doctor object.
        /// </summary>
        /// <param name="id_doctor">Initial value of the id_doctor property.</param>
        /// <param name="spec_id">Initial value of the spec_id property.</param>
        public static doctor Createdoctor(global::System.Int32 id_doctor, global::System.Int32 spec_id)
        {
            doctor doctor = new doctor();
            doctor.id_doctor = id_doctor;
            doctor.spec_id = spec_id;
            return doctor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_doctor
        {
            get
            {
                return _id_doctor;
            }
            set
            {
                if (_id_doctor != value)
                {
                    Onid_doctorChanging(value);
                    ReportPropertyChanging("id_doctor");
                    _id_doctor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_doctor");
                    Onid_doctorChanged();
                }
            }
        }
        private global::System.Int32 _id_doctor;
        partial void Onid_doctorChanging(global::System.Int32 value);
        partial void Onid_doctorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 spec_id
        {
            get
            {
                return _spec_id;
            }
            set
            {
                Onspec_idChanging(value);
                ReportPropertyChanging("spec_id");
                _spec_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("spec_id");
                Onspec_idChanged();
            }
        }
        private global::System.Int32 _spec_id;
        partial void Onspec_idChanging(global::System.Int32 value);
        partial void Onspec_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room
        {
            get
            {
                return _room;
            }
            set
            {
                OnroomChanging(value);
                ReportPropertyChanging("room");
                _room = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("room");
                OnroomChanged();
            }
        }
        private Nullable<global::System.Int32> _room;
        partial void OnroomChanging(Nullable<global::System.Int32> value);
        partial void OnroomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship1", "healing")]
        public EntityCollection<healing> healing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<healing>("hc_dbModel.Relationship1", "healing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<healing>("hc_dbModel.Relationship1", "healing", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="healing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class healing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new healing object.
        /// </summary>
        /// <param name="id_healing">Initial value of the id_healing property.</param>
        /// <param name="id_doctor">Initial value of the id_doctor property.</param>
        /// <param name="id_patient">Initial value of the id_patient property.</param>
        public static healing Createhealing(global::System.Int32 id_healing, global::System.Int32 id_doctor, global::System.Int32 id_patient)
        {
            healing healing = new healing();
            healing.id_healing = id_healing;
            healing.id_doctor = id_doctor;
            healing.id_patient = id_patient;
            return healing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_healing
        {
            get
            {
                return _id_healing;
            }
            set
            {
                if (_id_healing != value)
                {
                    Onid_healingChanging(value);
                    ReportPropertyChanging("id_healing");
                    _id_healing = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_healing");
                    Onid_healingChanged();
                }
            }
        }
        private global::System.Int32 _id_healing;
        partial void Onid_healingChanging(global::System.Int32 value);
        partial void Onid_healingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_doctor
        {
            get
            {
                return _id_doctor;
            }
            set
            {
                Onid_doctorChanging(value);
                ReportPropertyChanging("id_doctor");
                _id_doctor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_doctor");
                Onid_doctorChanged();
            }
        }
        private global::System.Int32 _id_doctor;
        partial void Onid_doctorChanging(global::System.Int32 value);
        partial void Onid_doctorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                Onid_patientChanging(value);
                ReportPropertyChanging("id_patient");
                _id_patient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_patient");
                Onid_patientChanged();
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String diagnosis
        {
            get
            {
                return _diagnosis;
            }
            set
            {
                OndiagnosisChanging(value);
                ReportPropertyChanging("diagnosis");
                _diagnosis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("diagnosis");
                OndiagnosisChanged();
            }
        }
        private global::System.String _diagnosis;
        partial void OndiagnosisChanging(global::System.String value);
        partial void OndiagnosisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String drugs
        {
            get
            {
                return _drugs;
            }
            set
            {
                OndrugsChanging(value);
                ReportPropertyChanging("drugs");
                _drugs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("drugs");
                OndrugsChanged();
            }
        }
        private global::System.String _drugs;
        partial void OndrugsChanging(global::System.String value);
        partial void OndrugsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> healing_time
        {
            get
            {
                return _healing_time;
            }
            set
            {
                Onhealing_timeChanging(value);
                ReportPropertyChanging("healing_time");
                _healing_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("healing_time");
                Onhealing_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _healing_time;
        partial void Onhealing_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onhealing_timeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship1", "doctor")]
        public doctor doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<doctor> doctorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship3", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("hc_dbModel.Relationship3", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new patient object.
        /// </summary>
        /// <param name="id_patient">Initial value of the id_patient property.</param>
        /// <param name="safety_card">Initial value of the Safety_card property.</param>
        public static patient Createpatient(global::System.Int32 id_patient, global::System.Int32 safety_card)
        {
            patient patient = new patient();
            patient.id_patient = id_patient;
            patient.Safety_card = safety_card;
            return patient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                if (_id_patient != value)
                {
                    Onid_patientChanging(value);
                    ReportPropertyChanging("id_patient");
                    _id_patient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_patient");
                    Onid_patientChanged();
                }
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Safety_card
        {
            get
            {
                return _Safety_card;
            }
            set
            {
                OnSafety_cardChanging(value);
                ReportPropertyChanging("Safety_card");
                _Safety_card = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Safety_card");
                OnSafety_cardChanged();
            }
        }
        private global::System.Int32 _Safety_card;
        partial void OnSafety_cardChanging(global::System.Int32 value);
        partial void OnSafety_cardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private Nullable<global::System.Int32> _tel;
        partial void OntelChanging(Nullable<global::System.Int32> value);
        partial void OntelChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship4", "analis")]
        public EntityCollection<analis> analis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<analis>("hc_dbModel.Relationship4", "analis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<analis>("hc_dbModel.Relationship4", "analis", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship3", "healing")]
        public EntityCollection<healing> healing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<healing>("hc_dbModel.Relationship3", "healing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<healing>("hc_dbModel.Relationship3", "healing", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="spec")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class spec : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spec object.
        /// </summary>
        /// <param name="spec_id">Initial value of the spec_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static spec Createspec(global::System.Int32 spec_id, global::System.String name)
        {
            spec spec = new spec();
            spec.spec_id = spec_id;
            spec.name = name;
            return spec;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 spec_id
        {
            get
            {
                return _spec_id;
            }
            set
            {
                if (_spec_id != value)
                {
                    Onspec_idChanging(value);
                    ReportPropertyChanging("spec_id");
                    _spec_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("spec_id");
                    Onspec_idChanged();
                }
            }
        }
        private global::System.Int32 _spec_id;
        partial void Onspec_idChanging(global::System.Int32 value);
        partial void Onspec_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }

    #endregion
    
}
