//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship4", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.patient), "analis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.analis), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship1", "doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.doctor), "healing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.healing), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship5", "spec", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.spec), "doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.doctor), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship7", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.user), "doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.doctor), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship3", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.patient), "healing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.healing), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship8", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.user), "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.patient), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship6", "user_type", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.user_type), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.user), true)]
[assembly: EdmRelationshipAttribute("hc_dbModel", "Relationship9", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(hospital.department), "spec", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(hospital.spec), true)]

#endregion

namespace hospital
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class hc_dbEntities1 : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект hc_dbEntities1, используя строку соединения из раздела "hc_dbEntities1" файла конфигурации приложения.
        /// </summary>
        public hc_dbEntities1() : base("name=hc_dbEntities1", "hc_dbEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта hc_dbEntities1.
        /// </summary>
        public hc_dbEntities1(string connectionString) : base(connectionString, "hc_dbEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта hc_dbEntities1.
        /// </summary>
        public hc_dbEntities1(EntityConnection connection) : base(connection, "hc_dbEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<analis> analis
        {
            get
            {
                if ((_analis == null))
                {
                    _analis = base.CreateObjectSet<analis>("analis");
                }
                return _analis;
            }
        }
        private ObjectSet<analis> _analis;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<doctor> doctor
        {
            get
            {
                if ((_doctor == null))
                {
                    _doctor = base.CreateObjectSet<doctor>("doctor");
                }
                return _doctor;
            }
        }
        private ObjectSet<doctor> _doctor;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<healing> healing
        {
            get
            {
                if ((_healing == null))
                {
                    _healing = base.CreateObjectSet<healing>("healing");
                }
                return _healing;
            }
        }
        private ObjectSet<healing> _healing;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<patient> patient
        {
            get
            {
                if ((_patient == null))
                {
                    _patient = base.CreateObjectSet<patient>("patient");
                }
                return _patient;
            }
        }
        private ObjectSet<patient> _patient;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<spec> spec
        {
            get
            {
                if ((_spec == null))
                {
                    _spec = base.CreateObjectSet<spec>("spec");
                }
                return _spec;
            }
        }
        private ObjectSet<spec> _spec;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<user_type> user_type
        {
            get
            {
                if ((_user_type == null))
                {
                    _user_type = base.CreateObjectSet<user_type>("user_type");
                }
                return _user_type;
            }
        }
        private ObjectSet<user_type> _user_type;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<department> department
        {
            get
            {
                if ((_department == null))
                {
                    _department = base.CreateObjectSet<department>("department");
                }
                return _department;
            }
        }
        private ObjectSet<department> _department;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet analis. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToanalis(analis analis)
        {
            base.AddObject("analis", analis);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet doctor. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTodoctor(doctor doctor)
        {
            base.AddObject("doctor", doctor);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet healing. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTohealing(healing healing)
        {
            base.AddObject("healing", healing);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet patient. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTopatient(patient patient)
        {
            base.AddObject("patient", patient);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet spec. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTospec(spec spec)
        {
            base.AddObject("spec", spec);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet user. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet user_type. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTouser_type(user_type user_type)
        {
            base.AddObject("user_type", user_type);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet department. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTodepartment(department department)
        {
            base.AddObject("department", department);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="analis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class analis : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта analis.
        /// </summary>
        /// <param name="id_analis">Исходное значение свойства id_analis.</param>
        /// <param name="id_patient">Исходное значение свойства id_patient.</param>
        public static analis Createanalis(global::System.Int32 id_analis, global::System.Int32 id_patient)
        {
            analis analis = new analis();
            analis.id_analis = id_analis;
            analis.id_patient = id_patient;
            return analis;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_analis
        {
            get
            {
                return _id_analis;
            }
            set
            {
                if (_id_analis != value)
                {
                    Onid_analisChanging(value);
                    ReportPropertyChanging("id_analis");
                    _id_analis = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_analis");
                    Onid_analisChanged();
                }
            }
        }
        private global::System.Int32 _id_analis;
        partial void Onid_analisChanging(global::System.Int32 value);
        partial void Onid_analisChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                Onid_patientChanging(value);
                ReportPropertyChanging("id_patient");
                _id_patient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_patient");
                Onid_patientChanged();
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String conclusion
        {
            get
            {
                return _conclusion;
            }
            set
            {
                OnconclusionChanging(value);
                ReportPropertyChanging("conclusion");
                _conclusion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("conclusion");
                OnconclusionChanged();
            }
        }
        private global::System.String _conclusion;
        partial void OnconclusionChanging(global::System.String value);
        partial void OnconclusionChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship4", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship4", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("hc_dbModel.Relationship4", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта department.
        /// </summary>
        /// <param name="id_department">Исходное значение свойства id_department.</param>
        /// <param name="name">Исходное значение свойства name.</param>
        public static department Createdepartment(global::System.Int32 id_department, global::System.String name)
        {
            department department = new department();
            department.id_department = id_department;
            department.name = name;
            return department;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_department
        {
            get
            {
                return _id_department;
            }
            set
            {
                if (_id_department != value)
                {
                    Onid_departmentChanging(value);
                    ReportPropertyChanging("id_department");
                    _id_department = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_department");
                    Onid_departmentChanged();
                }
            }
        }
        private global::System.Int32 _id_department;
        partial void Onid_departmentChanging(global::System.Int32 value);
        partial void Onid_departmentChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship9", "spec")]
        public EntityCollection<spec> spec
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<spec>("hc_dbModel.Relationship9", "spec");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<spec>("hc_dbModel.Relationship9", "spec", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="doctor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class doctor : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта doctor.
        /// </summary>
        /// <param name="id_doctor">Исходное значение свойства id_doctor.</param>
        /// <param name="id_user">Исходное значение свойства id_user.</param>
        /// <param name="id_spec">Исходное значение свойства id_spec.</param>
        public static doctor Createdoctor(global::System.Int32 id_doctor, global::System.Int32 id_user, global::System.Int32 id_spec)
        {
            doctor doctor = new doctor();
            doctor.id_doctor = id_doctor;
            doctor.id_user = id_user;
            doctor.id_spec = id_spec;
            return doctor;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_doctor
        {
            get
            {
                return _id_doctor;
            }
            set
            {
                if (_id_doctor != value)
                {
                    Onid_doctorChanging(value);
                    ReportPropertyChanging("id_doctor");
                    _id_doctor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_doctor");
                    Onid_doctorChanged();
                }
            }
        }
        private global::System.Int32 _id_doctor;
        partial void Onid_doctorChanging(global::System.Int32 value);
        partial void Onid_doctorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_spec
        {
            get
            {
                return _id_spec;
            }
            set
            {
                Onid_specChanging(value);
                ReportPropertyChanging("id_spec");
                _id_spec = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_spec");
                Onid_specChanged();
            }
        }
        private global::System.Int32 _id_spec;
        partial void Onid_specChanging(global::System.Int32 value);
        partial void Onid_specChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room
        {
            get
            {
                return _room;
            }
            set
            {
                OnroomChanging(value);
                ReportPropertyChanging("room");
                _room = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("room");
                OnroomChanged();
            }
        }
        private Nullable<global::System.Int32> _room;
        partial void OnroomChanging(Nullable<global::System.Int32> value);
        partial void OnroomChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship1", "healing")]
        public EntityCollection<healing> healing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<healing>("hc_dbModel.Relationship1", "healing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<healing>("hc_dbModel.Relationship1", "healing", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship5", "spec")]
        public spec spec
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<spec>("hc_dbModel.Relationship5", "spec").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<spec>("hc_dbModel.Relationship5", "spec").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<spec> specReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<spec>("hc_dbModel.Relationship5", "spec");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<spec>("hc_dbModel.Relationship5", "spec", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship7", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship7", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship7", "user").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship7", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("hc_dbModel.Relationship7", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="healing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class healing : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта healing.
        /// </summary>
        /// <param name="id_healing">Исходное значение свойства id_healing.</param>
        /// <param name="id_doctor">Исходное значение свойства id_doctor.</param>
        /// <param name="id_patient">Исходное значение свойства id_patient.</param>
        /// <param name="healing_time">Исходное значение свойства healing_time.</param>
        public static healing Createhealing(global::System.Int32 id_healing, global::System.Int32 id_doctor, global::System.Int32 id_patient, global::System.DateTime healing_time)
        {
            healing healing = new healing();
            healing.id_healing = id_healing;
            healing.id_doctor = id_doctor;
            healing.id_patient = id_patient;
            healing.healing_time = healing_time;
            return healing;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_healing
        {
            get
            {
                return _id_healing;
            }
            set
            {
                if (_id_healing != value)
                {
                    Onid_healingChanging(value);
                    ReportPropertyChanging("id_healing");
                    _id_healing = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_healing");
                    Onid_healingChanged();
                }
            }
        }
        private global::System.Int32 _id_healing;
        partial void Onid_healingChanging(global::System.Int32 value);
        partial void Onid_healingChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_doctor
        {
            get
            {
                return _id_doctor;
            }
            set
            {
                Onid_doctorChanging(value);
                ReportPropertyChanging("id_doctor");
                _id_doctor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_doctor");
                Onid_doctorChanged();
            }
        }
        private global::System.Int32 _id_doctor;
        partial void Onid_doctorChanging(global::System.Int32 value);
        partial void Onid_doctorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                Onid_patientChanging(value);
                ReportPropertyChanging("id_patient");
                _id_patient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_patient");
                Onid_patientChanged();
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String diagnosis
        {
            get
            {
                return _diagnosis;
            }
            set
            {
                OndiagnosisChanging(value);
                ReportPropertyChanging("diagnosis");
                _diagnosis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("diagnosis");
                OndiagnosisChanged();
            }
        }
        private global::System.String _diagnosis;
        partial void OndiagnosisChanging(global::System.String value);
        partial void OndiagnosisChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String drugs
        {
            get
            {
                return _drugs;
            }
            set
            {
                OndrugsChanging(value);
                ReportPropertyChanging("drugs");
                _drugs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("drugs");
                OndrugsChanged();
            }
        }
        private global::System.String _drugs;
        partial void OndrugsChanging(global::System.String value);
        partial void OndrugsChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime healing_time
        {
            get
            {
                return _healing_time;
            }
            set
            {
                Onhealing_timeChanging(value);
                ReportPropertyChanging("healing_time");
                _healing_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("healing_time");
                Onhealing_timeChanged();
            }
        }
        private global::System.DateTime _healing_time;
        partial void Onhealing_timeChanging(global::System.DateTime value);
        partial void Onhealing_timeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship1", "doctor")]
        public doctor doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<doctor> doctorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<doctor>("hc_dbModel.Relationship1", "doctor", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship3", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("hc_dbModel.Relationship3", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("hc_dbModel.Relationship3", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта patient.
        /// </summary>
        /// <param name="id_patient">Исходное значение свойства id_patient.</param>
        /// <param name="id_user">Исходное значение свойства id_user.</param>
        /// <param name="safety_card">Исходное значение свойства Safety_card.</param>
        public static patient Createpatient(global::System.Int32 id_patient, global::System.Int32 id_user, global::System.Int32 safety_card)
        {
            patient patient = new patient();
            patient.id_patient = id_patient;
            patient.id_user = id_user;
            patient.Safety_card = safety_card;
            return patient;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_patient
        {
            get
            {
                return _id_patient;
            }
            set
            {
                if (_id_patient != value)
                {
                    Onid_patientChanging(value);
                    ReportPropertyChanging("id_patient");
                    _id_patient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_patient");
                    Onid_patientChanged();
                }
            }
        }
        private global::System.Int32 _id_patient;
        partial void Onid_patientChanging(global::System.Int32 value);
        partial void Onid_patientChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Safety_card
        {
            get
            {
                return _Safety_card;
            }
            set
            {
                OnSafety_cardChanging(value);
                ReportPropertyChanging("Safety_card");
                _Safety_card = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Safety_card");
                OnSafety_cardChanged();
            }
        }
        private global::System.Int32 _Safety_card;
        partial void OnSafety_cardChanging(global::System.Int32 value);
        partial void OnSafety_cardChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship4", "analis")]
        public EntityCollection<analis> analis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<analis>("hc_dbModel.Relationship4", "analis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<analis>("hc_dbModel.Relationship4", "analis", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship3", "healing")]
        public EntityCollection<healing> healing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<healing>("hc_dbModel.Relationship3", "healing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<healing>("hc_dbModel.Relationship3", "healing", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship8", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship8", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship8", "user").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("hc_dbModel.Relationship8", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("hc_dbModel.Relationship8", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="spec")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class spec : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта spec.
        /// </summary>
        /// <param name="id_spec">Исходное значение свойства id_spec.</param>
        /// <param name="name">Исходное значение свойства name.</param>
        /// <param name="id_department">Исходное значение свойства id_department.</param>
        public static spec Createspec(global::System.Int32 id_spec, global::System.String name, global::System.Int32 id_department)
        {
            spec spec = new spec();
            spec.id_spec = id_spec;
            spec.name = name;
            spec.id_department = id_department;
            return spec;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_spec
        {
            get
            {
                return _id_spec;
            }
            set
            {
                if (_id_spec != value)
                {
                    Onid_specChanging(value);
                    ReportPropertyChanging("id_spec");
                    _id_spec = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_spec");
                    Onid_specChanged();
                }
            }
        }
        private global::System.Int32 _id_spec;
        partial void Onid_specChanging(global::System.Int32 value);
        partial void Onid_specChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_department
        {
            get
            {
                return _id_department;
            }
            set
            {
                Onid_departmentChanging(value);
                ReportPropertyChanging("id_department");
                _id_department = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_department");
                Onid_departmentChanged();
            }
        }
        private global::System.Int32 _id_department;
        partial void Onid_departmentChanging(global::System.Int32 value);
        partial void Onid_departmentChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship5", "doctor")]
        public EntityCollection<doctor> doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<doctor>("hc_dbModel.Relationship5", "doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<doctor>("hc_dbModel.Relationship5", "doctor", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship9", "department")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("hc_dbModel.Relationship9", "department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("hc_dbModel.Relationship9", "department").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("hc_dbModel.Relationship9", "department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("hc_dbModel.Relationship9", "department", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта user.
        /// </summary>
        /// <param name="id_user">Исходное значение свойства id_user.</param>
        /// <param name="id_user_type">Исходное значение свойства id_user_type.</param>
        /// <param name="login">Исходное значение свойства login.</param>
        /// <param name="password">Исходное значение свойства password.</param>
        public static user Createuser(global::System.Int32 id_user, global::System.Int32 id_user_type, global::System.String login, global::System.String password)
        {
            user user = new user();
            user.id_user = id_user;
            user.id_user_type = id_user_type;
            user.login = login;
            user.password = password;
            return user;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                if (_id_user != value)
                {
                    Onid_userChanging(value);
                    ReportPropertyChanging("id_user");
                    _id_user = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_user");
                    Onid_userChanged();
                }
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user_type
        {
            get
            {
                return _id_user_type;
            }
            set
            {
                Onid_user_typeChanging(value);
                ReportPropertyChanging("id_user_type");
                _id_user_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user_type");
                Onid_user_typeChanged();
            }
        }
        private global::System.Int32 _id_user_type;
        partial void Onid_user_typeChanging(global::System.Int32 value);
        partial void Onid_user_typeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship7", "doctor")]
        public EntityCollection<doctor> doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<doctor>("hc_dbModel.Relationship7", "doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<doctor>("hc_dbModel.Relationship7", "doctor", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship8", "patient")]
        public EntityCollection<patient> patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<patient>("hc_dbModel.Relationship8", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<patient>("hc_dbModel.Relationship8", "patient", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship6", "user_type")]
        public user_type user_type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_type>("hc_dbModel.Relationship6", "user_type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_type>("hc_dbModel.Relationship6", "user_type").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user_type> user_typeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_type>("hc_dbModel.Relationship6", "user_type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user_type>("hc_dbModel.Relationship6", "user_type", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hc_dbModel", Name="user_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_type : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта user_type.
        /// </summary>
        /// <param name="id_user_type">Исходное значение свойства id_user_type.</param>
        /// <param name="name">Исходное значение свойства name.</param>
        public static user_type Createuser_type(global::System.Int32 id_user_type, global::System.String name)
        {
            user_type user_type = new user_type();
            user_type.id_user_type = id_user_type;
            user_type.name = name;
            return user_type;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user_type
        {
            get
            {
                return _id_user_type;
            }
            set
            {
                if (_id_user_type != value)
                {
                    Onid_user_typeChanging(value);
                    ReportPropertyChanging("id_user_type");
                    _id_user_type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_user_type");
                    Onid_user_typeChanged();
                }
            }
        }
        private global::System.Int32 _id_user_type;
        partial void Onid_user_typeChanging(global::System.Int32 value);
        partial void Onid_user_typeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hc_dbModel", "Relationship6", "user")]
        public EntityCollection<user> user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user>("hc_dbModel.Relationship6", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user>("hc_dbModel.Relationship6", "user", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
